# Generated by Django 5.1.6 on 2026-10-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepost',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Optional deadline for this announcement', null=True),
        ),
    ]
