# Generated by Django 5.1.6 on 2026-09-08 04:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('department', 'Department'), ('course', 'Course'), ('topic', 'Topic')], default='topic', max_length=20)),
            ],
            options={
                'ordering': ['kind', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('audience', models.CharField(choices=[('public', 'Everyone, including guests'), ('students', 'Signed-in students'), ('staff', 'Lecturers and department only')], default='public', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='faqs', to='announcements.tag')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['position', 'id'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='faq_search_gin')],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('public', 'Everyone, including guests'), ('students', 'Signed-in students'), ('staff', 'Lecturers and department only')], default='public', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('author_label', models.CharField(default='Department', max_length=80)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='announcements', to='announcements.tag')),
            ],
            options={
                'ordering': ['-is_urgent', '-published_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ann_search_gin'), models.Index(fields=['audience', '-published_at'], name='ann_audience_date')],
            },
        ),
    ]
