# Generated by Django 5.1.6 on 2026-09-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='kind',
            field=models.CharField(choices=[('department', 'Department'), ('course', 'Course'), ('lab', 'Lab'), ('topic', 'Topic')], default='topic', max_length=20),
        ),
    ]
