# Generated by Django 5.1.6 on 2026-09-02 10:28

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nisit_id', models.CharField(db_column='userID', max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Nisit ID must be exactly 10 digits, numbers only.', regex='^\\d{10}$')], verbose_name='Nisit ID')),
                ('first_name', models.CharField(db_column='userFirstName', max_length=150)),
                ('last_name', models.CharField(db_column='userLastName', max_length=150)),
                ('email', models.EmailField(db_column='userEmail', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Enter your KU email — it must end with @ku.th.', regex='^[^@\\s]+@ku\\.th$')], verbose_name='KU email')),
                ('department', models.CharField(choices=[('ske', 'Software & Knowledge Engineering'), ('cpe', 'Computer Engineering')], db_column='userDepartment', max_length=30)),
                ('password', models.CharField(db_column='userPassword', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(db_column='isDepartment', default=False)),
                ('is_staff', models.BooleanField(db_column='isLecturer', default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='createDate')),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
            ],
            options={
                'db_table': 'ISP_DJANGO_2026"."Users',
                'managed': False,
            },
        ),
    ]
