# Generated by Django 5.2.17 on 2026-09-02 02:42

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        flags=re.RegexFlag["IGNORECASE"],
                        message="Enter your KU email — it must end with @ku.th.",
                        regex="^[^@\\s]+@ku\\.th$",
                    )
                ],
                verbose_name="KU email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nisit_id",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Nisit ID must be exactly 10 digits, numbers only.",
                        regex="^\\d{10}$",
                    )
                ],
                verbose_name="Nisit ID",
            ),
        ),
    ]
